// <auto-generated />
namespace Task_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createisblock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createisblock));
        
        string IMigrationMetadata.Id
        {
            get { return "201802181031547_create isblock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
